### ISSUE TITLE
关于训练的一些问题

### ISSUE THREAD

**Issue by StrongerPeople** [seekerhuang/HarMA#4]
感谢您的工作和代码，我是一个深度学习小白，请问在训练代码中， for epoch in range(0, max_epoch):
            if args.distributed:
                train_loader.sampler.set_epoch(epoch)
            train_stats = train(model, train_loader, optimizer, tokenizer, epoch, device, lr_scheduler, config)
            # score_val_i2t, score_val_t2i, = evaluation(model_without_ddp, val_loader, tokenizer, device, config)
            score_test_i2t, score_test_t2i = evaluation(model_without_ddp, test_loader, tokenizer, device, config)

            if utils.is_main_process():
                # val_result = itm_eval(score_val_i2t, score_val_t2i, val_loader.dataset.txt2img, val_loader.dataset.img2txt)
                test_result = itm_eval(score_test_i2t, score_test_t2i, test_loader.dataset.txt2img, test_loader.dataset.img2txt)
                print(test_result)

                log_stats = {**{f'train_{k}': v for k, v in train_stats.items()},
                            #  **{f'val_{k}': v for k, v in val_result.items()},
                             **{f'test_{k}': v for k, v in test_result.items()},
                             'epoch': epoch}
                with open(os.path.join(args.output_dir, filename), "a") as f:
                    f.write(json.dumps(log_stats) + "\n")
                if test_result['r_mean'] > best:
                    save_obj = {
                        'model': model_without_ddp.state_dict(),
                        # 'optimizer': optimizer.state_dict(),
                        # 'lr_scheduler': lr_scheduler.state_dict(),
                        'config': config,
                        # 'epoch': epoch,
                    }
                    torch.save(save_obj, os.path.join(args.output_dir, 'checkpoint_best.pth'))
                    best = test_result['r_mean']
                    best_epoch = epoch，直接对测试集进行评估，并保存最好的结果，这样的操作是可行的嘛？

**Comment by seekerhuang** [comment]
评估代码基于[PIR](https://github.com/jaychempan/PIR)构建，为了便于使用该代码库的人能够较为容易地得出测试结果。实际上论文中报道的性能为多次实验的平均性能，反而是略低于所有实验中出现过的最佳结果（约1%左右）的。
